name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build -- --base /${{ github.event.repository.name }}/
      - name: Save build output
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
      - name: Save npm logs
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: npm-logs
          path: ~/.npm/_logs
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Save npm logs
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ secrets.AWS_S3_REGION }}
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_S3_ACCESS_KEY_SECRET }}
      - name: Deploy
        run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET }}/${{ github.event.repository.name }} --delete
      - name: Invalidate cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION }} --paths "/*"
